---
title: "draft"
author: "Hannah Luebbering"
date: "6/23/2020"
output: Markdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part One: Shiny

Shiny is an R package developed for building graphical, interactive, visual web apps. Through interface development around R, the Shiny software package makes it easier for computer operators to build and run web applications on various servers (Seal and Wild, 2018). Visual Outputs resemble an easy-to-visit website offering instant feedback from user input in the form of moving sliders or clicking buttons. The code written in the shiny application framework controls the interface. Within the framework, the Shiny package offers highly interactive tools such as widgets for simplicity of use for application programmers and users. Without needing to adjust the source code, users can interact with the flexible user interface and see the change of inputs immediately reflecting in the output. What's more, users can specify different assumptions, change parameters, run R code, and see the results.

Contrasted with traditional presentation methods, R Shiny has various advantages. For example, the R model and Shiny applications update quickly, leverage the power of R's publicly available packages, and make web applications accessible via the browser to those with no programming knowledge. The R programming environment and Shiny make it easy for production tools to perform statistical analysis. For example, the Shiny Web application is handy for building health economic models because they have highly uncertain or unknown parameters and analyze different populations. To list a few other real-world examples, Shiny helps develop and advance evidence syntheses, risk-of-bias assessment figures, biomedical applications, network meta-analysis, the value of information analysis, and more.

Using the Shiny application in the classroom, various instructors provided positive feedback on the web application framework in R, making it possible to create a user interface using dynamic methods and rapid analysis. Facilitating the development of new teaching tools, Shiny provides a framework for existing R code to produce dynamic web-based applications. Providing a fluid and dynamic presentations, Shiny provides virtually instantaneous input and output mechanisms and visualizations: adjustments in the app by moving sliders or clicking buttons and corresponding updates to the output plot or model. Allowing unhindered access, Shiny publishes online with a web browser so "students can experiment with the app on their own without having to know anything about" programming or coding (Smith and Schneider, 2020). Preventing long pauses caused by code submission, R works discreetly in the background and interactively with Shiny.

Using Shiny for a randomized controlled trial and in-class simulation, Jimmy Doi built an in-class simulation enriched with the app's interactive web elements, fluid presentation, and dynamic user experience (Doi, 2016). Unlike the unstable traditional method, Shiny effectively conducts a comprehensive probability sensitivity analysis, which takes less time than the traditional method.


## Part Two: Learnr

The learner software package can turn any R Markdown document into a fascinating collaborative multimedia solution for teaching statistics and R programming. Building on R Markdown, the learnr package enables interactive tutorials featuring narratives, illustrations, figures, code snippets, code exercises, multiple-choice questions, videos, and other interactive shiny components. For example, the code exercises created in the learner package display as R code blocks, and the user can edit and execute them directly. There is no fear of losing accumulated hard work and progress when leaving the site in the learner-based tutorial. Automatically preserving work, tutorials allow users to save and keep track of progress on completed exercises or questions. After leaving, all the tutorial changes will save, so the user can continue to practice from the most recent changes. The learnr package supports teachers in creating interactive tutorials built with tools for “checking and reinforcing students’ understanding” while implementing a self-paced structure with instant feedback. The learnr package offers a platform where students are free to adjust code-snippets, complete coding exercises, read hints and solutions, and execute their code. In conclusion, the learnr package is a great tool to embrace modeling exercises as expedients to help other people learn something new using an interactive and self-paced platform.

